spring:
  application:
    name: greeting-kafka-streams
  profile:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: greeting-kafka-stream